### ISSUE TITLE
youtube playback addon not working on 2.513

### ISSUE THREAD

**Issue by CrYpT0n1T3** [volumio/volumio-plugins#284]
The plugin connected to my Google youtube account has stopped working after the upgrade. No results, nothing is displayed. After reboot, when I run youtube a red window "error no results" appears and a blue window "fetching data ..." No result

`Dec 11 11:30:18 volumio volumio[869]: error: Access Not Configured. YouTube Data API has not been used in project 119103001349 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/youtube.googleapis.com/overview?project=119103001349 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.

Dec 11 11:30:18 volumio volumio[869]: Error: Access Not Configured. YouTube Data API has not been used in project 119103001349 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/youtube.googleapis.com/overview?project=119103001349 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.

Dec 11 11:30:18 volumio volumio[869]: at Request._callback (/data/plugins/music_service/youtube/node_modules/google-auth-library/lib/transporters.js:85:15)`

**Comment by cmoulliard** [comment]
I can reproduce the error too and when I look to the volumio log, I see also this error 

```
2018-12-21T17:52:03.614Z - info: CoreCommandRouter::executeOnPlugin: youtube , handleBrowseUri
2018-12-21T17:52:03.615Z - info: handleBrowseUri: youtube
2018-12-21T17:52:03.839Z - error: Access Not Configured. YouTube Data API has not been used in project 119103001349 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/youtube.googleapis.com/overview?project=119103001349 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
Error: Access Not Configured. YouTube Data API has not been used in project 119103001349 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/youtube.googleapis.com/overview?project=119103001349 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
    at Request._callback (/data/plugins/music_service/youtube/node_modules/google-auth-library/lib/transporters.js:85:15)
    at Request.self.callback (/data/plugins/music_service/youtube/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/data/plugins/music_service/youtube/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/data/plugins/music_service/youtube/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

If we open the link, within a web browser, then we will get this message 

![screenshot 2018-12-21 18 59 13](https://user-images.githubusercontent.com/463790/50356515-85b1f400-0552-11e9-98d7-6053d4b3e7c5.png)

Is it because you have to review the updated terms ?

**Comment by CrYpT0n1T3** [comment]
I have changed the api keys to my api keys but then does not ask me for the code when connecting to the account goolge; [

**Comment by Testato** [comment]
Confirmed on last volumio  version also (upgraded today)

I tried also to reregister volumio on device google page without result

**Comment by tsrubar** [comment]
Any update on this? Exactly same behavior on 2.555
thx

**Comment by majko96** [comment]
please, fix youtube plugin...
