### ISSUE TITLE
Problems with Youtube Plugin / Videos not showing up

### ISSUE THREAD

**Issue by Renegat27** [volumio/volumio-plugins#351]
Hello, 
I have set up Volumio in the Version 2.599 on a RasPi3 with only the plugin for youtube (Version 0.1.0) installed. However if I open youtube, i won't get any results, just the following messages:
![Volumio_error](https://user-images.githubusercontent.com/54477511/63794041-57668e80-c901-11e9-9405-e692025f7475.jpg)

Searching something will only result in another message that it might take a while but there are no results presented after 10min, so i guess there is something not working properly.

Digging through the log brought up this here, hope it helps:

`2019-08-27T17:29:36.025Z - error: Access Not Configured. YouTube Data API has not been used in project 119103001349 before or it is disabled. Enable it by visiting https://console.develope$
Error: Access Not Configured. YouTube Data API has not been used in project 119103001349 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/yout$
    at Request._callback (/data/plugins/music_service/youtube/node_modules/google-auth-library/lib/transporters.js:85:15)
    at Request.self.callback (/data/plugins/music_service/youtube/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/data/plugins/music_service/youtube/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/data/plugins/music_service/youtube/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
`

Is it a general problem or did i do something wrong during installation/setup?
Best regards,
Renegat27

**Comment by balbuze** [comment]
Go in the plugin settings and follow instructions about grant access.
