### ISSUE TITLE
Podcast plugin crash

### ISSUE THREAD

**Issue by volumio** [volumio/volumio-plugins#374]
@ChrisPanda 
We had a report of the podcast plugin crashing volumio. here's the stack trace:
Nov 03 15:23:23 volumio volumio[30443]: |||||||||||||||||||||||| WARNING: FATAL ERROR |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
Nov 03 15:23:23 volumio volumio[30443]: TypeError: Cannot read property 'url' of undefined
Nov 03 15:23:23 volumio volumio[30443]: at /data/plugins/music_service/podcast/index.js:428:32
Nov 03 15:23:23 volumio volumio[30443]: at Array.some (<anonymous>)
Nov 03 15:23:23 volumio volumio[30443]: at /data/plugins/music_service/podcast/index.js:419:18
Nov 03 15:23:23 volumio volumio[30443]: at Timeout.setTimeout [as _onTimeout] (/data/plugins/music_service/podcast/node_modules/rss-parser/lib/utils.js:53:30)
Nov 03 15:23:23 volumio volumio[30443]: at ontimeout (timers.js:482:11)
Nov 03 15:23:23 volumio volumio[30443]: at tryOnTimeout (timers.js:317:5)
Nov 03 15:23:23 volumio volumio[30443]: at Timer.listOnTimeout (timers.js:277:5)
Nov 03 15:23:23 volumio volumio[30443]: |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||

Can you please have a look and fix it?

**Comment by ChrisPanda** [comment]
Hi,

I already fixed at version 0.2.0. The fixed version was pull request about 4 month ago that is named after "fix bbc podcast radio list error". So you can merge my podcast pull request and that problem will be resolved.

Thanks.
Chris Song
