### ISSUE TITLE
Youtube Access Not Configured

### ISSUE THREAD

**Issue by martin640** [volumio/volumio-plugins#421]
```
Mar 03 16:56:54 volumio-martin volumio[984]: info: CoreCommandRouter::executeOnPlugin: youtube , handleBrowseUri
Mar 03 16:56:54 volumio-martin volumio[984]: info: handleBrowseUri: youtube
Mar 03 16:56:57 volumio-martin volumio[984]: info: CoreCommandRouter::executeOnPlugin: youtube , handleBrowseUri
Mar 03 16:56:57 volumio-martin volumio[984]: info: handleBrowseUri: youtube/root/likedVideos
Mar 03 16:56:57 volumio-martin volumio[984]: error: Access Not Configured. YouTube Data API has not been used in project 846464762843 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/youtube.googleapis.com/overview?project=846464762843 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
Mar 03 16:56:57 volumio-martin volumio[984]: Error: Access Not Configured. YouTube Data API has not been used in project 846464762843 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/youtube.googleapis.com/overview?project=846464762843 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
Mar 03 16:56:57 volumio-martin volumio[984]: at Request._callback (/data/plugins/music_service/youtube/node_modules/google-auth-library/lib/transporters.js:85:15)
Mar 03 16:56:57 volumio-martin volumio[984]: at Request.self.callback (/data/plugins/music_service/youtube/node_modules/request/request.js:185:22)
Mar 03 16:56:57 volumio-martin volumio[984]: at emitTwo (events.js:126:13)
Mar 03 16:56:57 volumio-martin volumio[984]: at Request.emit (events.js:214:7)
Mar 03 16:56:57 volumio-martin volumio[984]: at Request.<anonymous> (/data/plugins/music_service/youtube/node_modules/request/request.js:1154:10)
Mar 03 16:56:57 volumio-martin volumio[984]: at emitOne (events.js:116:13)
Mar 03 16:56:57 volumio-martin volumio[984]: at Request.emit (events.js:211:7)
Mar 03 16:56:57 volumio-martin volumio[984]: at IncomingMessage.<anonymous> (/data/plugins/music_service/youtube/node_modules/request/request.js:1076:12)
Mar 03 16:56:57 volumio-martin volumio[984]: at Object.onceWrapper (events.js:313:30)
Mar 03 16:56:57 volumio-martin volumio[984]: at emitNone (events.js:111:20)
Mar 03 16:56:57 volumio-martin volumio[984]: at IncomingMessage.emit (events.js:208:7)
Mar 03 16:56:57 volumio-martin volumio[984]: at endReadableNT (_stream_readable.js:1064:12)
Mar 03 16:56:57 volumio-martin volumio[984]: at _combinedTickCallback (internal/process/next_tick.js:138:11)
Mar 03 16:56:57 volumio-martin volumio[984]: at process._tickCallback (internal/process/next_tick.js:180:9)
Mar 03 16:56:57 volumio-martin volumio[984]: error: Failed to execute browseSource: Error: Access Not Configured. YouTube Data API has not been used in project 846464762843 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/youtube.googleapis.com/overview?project=846464762843 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
```

**Comment by volumio** [comment]
See : https://forum.volumio.org/youtube-for-volumio-t6608-320.html#p73133
