### ISSUE TITLE
Rotary encoder plugin not storing configuration after reset

### ISSUE THREAD

**Issue by dubaleeiro** [volumio/volumio-plugins#423]
Hello,

for some reason I can't understand, the rotary encoder configuration (pins, detent action, etc) is "lost" after rebooting the Pi and only gets back to work when the configuration is saved in the UI.

I have noticed the file '/data/configuration/user_interface/rotaryencoder/config.json' changes accordingly, but the file '/data/plugins/user_interface/rotaryencoder/config.json' don't. Well, I tried to change this one manually and it didn't work either.

Can anyone help me on that? Thank you!

Raspberry Pi Zero W V1.1
Innomaker HiFi AMP Hat
System Version: 2.714
Plugin Rotary Encoder 1.2.2 (maybe obvious information after the one above...)
Encoder #1: CLK=24; DT=23;detent action=1 (volume control)
Encoder #2: CLK=8; DT=25;detent action=2 (prev/next)

**Comment by balbuze** [comment]
hello,
 '/data/plugins/user_interface/rotaryencoder/config.json'  is the default config file when you install the plugin. You are not supposed to change it.
 '/data/configuration/user_interface/rotaryencoder/config.json' is the file where config is saved when you save in the config page. So if your values are save here, everything is ok!

**Comment by dubaleeiro** [comment]
Hi,
values are correctly saved in the '/data/configuration/user_interface/rotaryencoder/config.json' file. The problem is that after the Pi is reset the only way to make the rotary encoder to work is to ckick 'save' in the config page again. Any possible reasons for that?

This is the LOG file, if it helps...
Thanks!

`volumio@volumio:~$ sudo journalctl -f
-- Logs begin at Sun 2020-03-08 15:18:14 UTC. --
Mar 08 15:19:58 volumio systemd[915]: Startup finished in 192ms.
Mar 08 15:19:58 volumio systemd[1]: Started User Manager for UID 1000.
Mar 08 15:19:58 volumio sshd[899]: lastlog_openseek: Couldn't stat /var/log/lastlog: No such file or directory
Mar 08 15:19:58 volumio sshd[899]: lastlog_openseek: Couldn't stat /var/log/lastlog: No such file or directory
Mar 08 15:19:58 volumio volumio[867]: info: Loading plugin "upnp_browser"...
Mar 08 15:20:00 volumio volumio[867]: info: Loading plugin "networkfs"...
Mar 08 15:20:01 volumio volumio[867]: info: CoreCommandRouter::executeOnPlugin: system , registerCallback
Mar 08 15:20:01 volumio volumio[867]: info: Loading plugin "alarm-clock"...
Mar 08 15:20:01 volumio sudo[930]: volumio : TTY=pts/0 ; PWD=/home/volumio ; USER=root ; COMMAND=/bin/journalctl -f
Mar 08 15:20:01 volumio sudo[930]: pam_unix(sudo:session): session opened for user root by volumio(uid=0)
Mar 08 15:20:02 volumio volumio[867]: info: Loading plugin "airplay_emulation"...
Mar 08 15:20:02 volumio volumio[867]: info: Starting Shairport Sync
Mar 08 15:20:02 volumio volumio[867]: info: Loading plugin "last_100"...
Mar 08 15:20:02 volumio volumio[867]: info: Loading plugin "webradio"...
Mar 08 15:20:03 volumio volumio[867]: info: Loading plugin "i2s_dacs"...
Mar 08 15:20:03 volumio volumio[867]: info: CoreCommandRouter::executeOnPlugin: system , getConfigParam
Mar 08 15:20:03 volumio volumio[867]: info: Loading plugin "volumiodiscovery"...
Mar 08 15:20:03 volumio volumio[867]: *** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
Mar 08 15:20:03 volumio node[867]: *** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
Mar 08 15:20:03 volumio node[867]: *** WARNING *** Please fix your application to use the native API of Avahi!
Mar 08 15:20:03 volumio node[867]: *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
Mar 08 15:20:03 volumio node[867]: *** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
Mar 08 15:20:03 volumio node[867]: *** WARNING *** Please fix your application to use the native API of Avahi!
Mar 08 15:20:03 volumio node[867]: *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
Mar 08 15:20:03 volumio volumio[867]: *** WARNING *** Please fix your application to use the native API of Avahi!
Mar 08 15:20:03 volumio volumio[867]: *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
Mar 08 15:20:03 volumio volumio[867]: *** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
Mar 08 15:20:03 volumio volumio[867]: *** WARNING *** Please fix your application to use the native API of Avahi!
Mar 08 15:20:03 volumio volumio[867]: *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
Mar 08 15:20:03 volumio volumio[867]: info: Applying required configuration parameters for plugin volumiodiscovery
Mar 08 15:20:03 volumio volumio[867]: Discovery: StartAdv! undefined
Mar 08 15:20:03 volumio volumio[867]: Discovery: Started advertising... Volumio - undefined
Mar 08 15:20:03 volumio volumio[867]: info: CoreCommandRouter::executeOnPlugin: system , registerCallback
Mar 08 15:20:03 volumio volumio[867]: info: Loading plugin "outputs"...
Mar 08 15:20:03 volumio volumio[867]: info: Loading plugin "albumart"...
Mar 08 15:20:03 volumio volumio[867]: info: Plugin example_plugin is not enabled
Mar 08 15:20:03 volumio volumio[867]: info: Loading plugin "inputs"...
Mar 08 15:20:03 volumio volumio[867]: info: Loading plugin "updater_comm"...
Mar 08 15:20:05 volumio volumio[867]: info: Plugin mpdemulation is not enabled
Mar 08 15:20:05 volumio volumio[867]: info: Loading plugin "rest_api"...
Mar 08 15:20:05 volumio volumio[867]: info: Loading plugin "websocket"...
Mar 08 15:20:05 volumio volumio[867]: info: Loading plugin "spop"...
Mar 08 15:20:06 volumio volumio[867]: Forking 1 albumart workers
Mar 08 15:20:09 volumio volumio-remote-updater[469]: [2020-03-08 15:20:09] [connect] Successful connection
Mar 08 15:20:12 volumio volumio[867]: info: Loading plugin "rotaryencoder"...
Mar 08 15:20:12 volumio volumio[867]: Starting albumart workers
Mar 08 15:20:15 volumio volumio[867]: info: Applying required configuration parameters for plugin rotaryencoder
Mar 08 15:20:16 volumio volumio[867]: info: ___________ START PLUGINS ___________
Mar 08 15:20:16 volumio volumio[867]: info: CoreCommandRouter::executeOnPlugin: mpd , getConfigParam
Mar 08 15:20:16 volumio volumio[867]: info: CoreCommandRouter::volumioAddToBrowseSources[object Object]
Mar 08 15:20:16 volumio volumio[867]: info: [1583680816053] CoreMusicLibrary::Adding element Media Servers
Mar 08 15:20:16 volumio volumio[867]: info: CoreCommandRouter::executeOnPlugin: my_music , getDisabledSources
Mar 08 15:20:16 volumio volumio[867]: info: CoreCommandRouter::executeOnPlugin: alsa_controller , getConfigParam
Mar 08 15:20:16 volumio volumio[867]: info: Could not detect Primo: Error: Command failed: aplay -l | grep es90x8q2m-dac-dai-0
Mar 08 15:20:16 volumio volumio[867]: info: CoreCommandRouter::executeOnPlugin: alsa_controller , getConfigParam
Mar 08 15:20:16 volumio volumio[867]: info: Could not detect Primo: Error: Command failed: aplay -l | grep es90x8q2m-dac-dai-0
Mar 08 15:20:16 volumio volumio[867]: info: CoreCommandRouter::volumioAddToBrowseSources[object Object]
Mar 08 15:20:16 volumio volumio[867]: info: [1583680816593] CoreMusicLibrary::Adding element Last_100
Mar 08 15:20:16 volumio volumio[867]: info: CoreCommandRouter::executeOnPlugin: my_music , getDisabledSources
Mar 08 15:20:16 volumio volumio[867]: info: CoreCommandRouter::volumioAddToBrowseSources[object Object]
Mar 08 15:20:16 volumio volumio[867]: info: [1583680816620] CoreMusicLibrary::Adding element Webradio
Mar 08 15:20:16 volumio volumio[867]: info: CoreCommandRouter::executeOnPlugin: my_music , getDisabledSources
Mar 08 15:20:16 volumio volumio[867]: info: CoreCommandRouter::executeOnPlugin: system , getSystemVersion
Mar 08 15:20:16 volumio volumio[867]: info: [Rotary encoder] Loaded configuration: {"longPressThresholdInMilliseconds":{"type":"int","value":1000},"first_encoder_CLK":{"type":"int","value":24},"first_encoder_DT":{"type":"int","value":23},"first_encoder_SW":{"type":"int","value":0},"first_encoder_encoding":{"type":"int","value":0},"first_encoder_detentActionType":{"type":"int","value":1},"first_encoder_buttonActionType":{"type":"int","value":0},"first_encoder_longPressActionType":{"type":"int","value":0},"second_encoder_CLK":{"type":"int","value":8},"second_encoder_DT":{"type":"int","value":25},"second_encoder_SW":{"type":"int","value":0},"second_encoder_encoding":{"type":"int","value":0},"second_encoder_detentActionType":{"type":"int","value":2},"second_encoder_buttonActionType":{"type":"int","value":0},"second_encoder_longPressActionType":{"type":"int","value":0},"enable_debug_logging":{"type":"boolean","value":true}}
Mar 08 15:20:16 volumio volumio[867]: info: -------------------------------------------
Mar 08 15:20:16 volumio volumio[867]: info: -----    MyVolumio plugins startup     ----
Mar 08 15:20:16 volumio volumio[867]: info: -------------------------------------------
Mar 08 15:20:16 volumio volumio[867]: info: [MyVolumio PluginManager] Fetching plans data....
Mar 08 15:20:16 volumio sudo[963]: volumio : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/systemctl start spop.service
Mar 08 15:20:16 volumio volumio[867]: info: Loading i18n strings for locale en
Mar 08 15:20:16 volumio sudo[963]: pam_unix(sudo:session): session opened for user root by (uid=0)
Mar 08 15:20:16 volumio volumio[867]: Updating browse sources language
Mar 08 15:20:16 volumio volumio[867]: Cannot find translation for sourceMedia Servers
Mar 08 15:20:16 volumio volumio[867]: info: CoreCommandRouter::executeOnPlugin: my_music , getDisabledSources
Mar 08 15:20:17 volumio systemd[1]: Configuration file /lib/systemd/system/spop.service is marked executable. Please remove executable permission bits. Proceeding anyway.
Mar 08 15:20:17 volumio systemd[1]: Configuration file /lib/systemd/system/spop.service is marked world-writable. Please remove world writability permission bits. Proceeding anyway.
Mar 08 15:20:17 volumio systemd[1]: Starting Spotify Daemon...
Mar 08 15:20:17 volumio systemd[1]: Started Spotify Daemon.
Mar 08 15:20:17 volumio volumio[867]: info: CoreCommandRouter::executeOnPlugin: mpd , getConfigParam
Mar 08 15:20:17 volumio volumio[867]: info: CoreCommandRouter::initPlayerControls
Mar 08 15:20:17 volumio volumio[867]: info: CoreCommandRouter::executeOnPlugin: alsa_controller , getConfigParam
Mar 08 15:20:17 volumio volumio[867]: info: CoreCommandRouter::executeOnPlugin: alsa_controller , getConfigParam
Mar 08 15:20:17 volumio volumio[867]: info: CoreCommandRouter::executeOnPlugin: alsa_controller , getConfigParam
Mar 08 15:20:17 volumio volumio[867]: info: CoreCommandRouter::executeOnPlugin: alsa_controller , getConfigParam
Mar 08 15:20:17 volumio volumio[867]: info: CoreCommandRouter::executeOnPlugin: alsa_controller , getConfigParam
Mar 08 15:20:17 volumio volumio[867]: info: CoreCommandRouter::executeOnPlugin: alsa_controller , getConfigParam
Mar 08 15:20:17 volumio volumio[867]: info: CoreCommandRouter::executeOnPlugin: alsa_controller , getConfigParam
Mar 08 15:20:17 volumio volumio[968]: 2020-03-08 15:20:17 [SPTF] 15:20:17.463 I [offline_authorizer.cpp:297] Unable to login offline: no such user
Mar 08 15:20:17 volumio volumio[968]: 2020-03-08 15:20:17 [SPTF] 15:20:17.514 I [ap:1752] Connecting to AP ap.spotify.com:4070
Mar 08 15:20:17 volumio volumio[867]: info: CoreCommandRouter::executeOnPlugin: mpd , getConfigParam
Mar 08 15:20:17 volumio volumio[867]: info: BOOT COMPLETED
Mar 08 15:20:17 volumio volumio[867]: info: CoreCommandRouter::executeOnPlugin: system , getConfigParam
Mar 08 15:20:17 volumio volumio[968]: 2020-03-08 15:20:17 [SPTF] 15:20:17.657 I [ap:1226] Connected to AP: 35.190.242.143:4070
Mar 08 15:20:18 volumio sudo[963]: pam_unix(sudo:session): session closed for user root
Mar 08 15:20:19 volumio volumio[968]: 2020-03-08 15:20:19 [SPTF] 15:20:19.812 I [offline-mgr:2030] 0 files are locked. 0 images are locked
Mar 08 15:20:19 volumio volumio[968]: 2020-03-08 15:20:19 [SPTF] 15:20:19.812 I [offline-mgr:2056] 0 files unlocked. 0 images unlocked
Mar 08 15:20:23 volumio volumio[867]: Playing WAVE '/volumio/app/startup.wav' : Signed 16 bit Little Endian, Rate 44100 Hz, Stereo
Mar 08 15:20:23 volumio volumio[867]: info: CoreCommandRouter::Close All Modals sent
Mar 08 15:20:23 volumio volumio[867]: info: CoreCommandRouter::Close All Modals sent
Mar 08 15:20:23 volumio volumio[867]: Express server listening on port 3000
Mar 08 15:20:23 volumio volumio[867]: Volumio Calling Home
Mar 08 15:20:23 volumio volumio[867]: info: CoreStateMachine::resetVolumioState
Mar 08 15:20:23 volumio volumio[867]: info: CoreStateMachine::getcurrentVolume
Mar 08 15:20:23 volumio volumio[867]: info: CoreCommandRouter::volumioRetrievevolume
Mar 08 15:20:24 volumio volumio-remote-updater[469]: [2020-03-08 15:20:24] [connect] Successful connection
Mar 08 15:20:24 volumio sudo[992]: volumio : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/sbin/ifconfig wlan0
Mar 08 15:20:24 volumio sudo[992]: pam_unix(sudo:session): session opened for user root by (uid=0)
Mar 08 15:20:24 volumio sudo[992]: pam_unix(sudo:session): session closed for user root
Mar 08 15:20:24 volumio volumio[867]: info: CoreCommandRouter::executeOnPlugin: alsa_controller , checkAudioDeviceAvailable
Mar 08 15:20:24 volumio volumio[867]: info: CoreCommandRouter::executeOnPlugin: raat , onStop
Mar 08 15:20:24 volumio volumio[867]: info: CoreCommandRouter::executeOnPlugin: system , versionChangeDetect
Mar 08 15:20:25 volumio volumio[867]: info: CoreStateMachine::pushState
Mar 08 15:20:25 volumio volumio[867]: info: CoreStateMachine::getState
Mar 08 15:20:25 volumio volumio[867]: info: CorePlayQueue::getTrack 0
Mar 08 15:20:25 volumio volumio[867]: info: CoreCommandRouter::volumioPushState
Mar 08 15:20:25 volumio volumio[867]: info: CoreCommandRouter::executeOnPlugin: volumiodiscovery , saveDeviceInfo
Mar 08 15:20:25 volumio volumio[867]: info: CoreStateMachine::updateTrackBlock
Mar 08 15:20:25 volumio volumio[867]: info: CorePlayQueue::getTrackBlock
Mar 08 15:20:25 volumio volumio[867]: info: CoreCommandRouter::volumioRetrievevolume
Mar 08 15:20:26 volumio volumio[867]: info: Volumio called home
Mar 08 15:20:26 volumio volumio[867]: info: Setting Device type: Raspberry PI
Mar 08 15:20:26 volumio volumio[867]: info: SpopD Daemon Started
Mar 08 15:20:26 volumio volumio[867]: info: MPD running with PID531 ,establishing connection
Mar 08 15:20:26 volumio volumio-remote-updater[469]: [2020-03-08 15:20:26] [connect] WebSocket Connection 127.0.0.1:3000 v-2 "WebSocket++/0.5.1" /socket.io/?EIO=4&transport=websocket&t=1583680824 101
Mar 08 15:20:26 volumio volumio[867]: info: CoreStateMachine::pushState
Mar 08 15:20:26 volumio volumio[867]: info: CoreStateMachine::getState
Mar 08 15:20:26 volumio volumio[867]: info: CorePlayQueue::getTrack 0
Mar 08 15:20:26 volumio volumio[867]: info: CoreCommandRouter::volumioPushState
Mar 08 15:20:26 volumio volumio[867]: info: CoreCommandRouter::executeOnPlugin: volumiodiscovery , saveDeviceInfo
Mar 08 15:20:28 volumio volumio[867]: info: Reloading queue from file
Mar 08 15:20:28 volumio volumio[867]: info:
Mar 08 15:20:28 volumio volumio[867]: info:  message= [50@0] {} No such directory, stack=Error:  [50@0] {} No such directory
Mar 08 15:20:28 volumio volumio[867]: at MpdClient.receive (/volumio/app/plugins/music_service/mpd/lib/mpd.js:63:14)
Mar 08 15:20:28 volumio volumio[867]: at Socket.<anonymous> (/volumio/app/plugins/music_service/mpd/lib/mpd.js:43:10)
Mar 08 15:20:28 volumio volumio[867]: at emitOne (events.js:116:13)
Mar 08 15:20:28 volumio volumio[867]: at Socket.emit (events.js:211:7)
Mar 08 15:20:28 volumio volumio[867]: at addChunk (_stream_readable.js:263:12)
Mar 08 15:20:28 volumio volumio[867]: at readableAddChunk (_stream_readable.js:246:13)
Mar 08 15:20:28 volumio volumio[867]: at Socket.Readable.push (_stream_readable.js:208:10)
Mar 08 15:20:28 volumio volumio[867]: at Pipe.onread (net.js:607:20)
Mar 08 15:20:28 volumio volumio[867]: info: CoreStateMachine::setRepeat null single undefined
Mar 08 15:20:28 volumio volumio[867]: info: CoreStateMachine::pushState
Mar 08 15:20:28 volumio volumio[867]: info: CoreStateMachine::getState
Mar 08 15:20:28 volumio volumio[867]: info: CorePlayQueue::getTrack 0
Mar 08 15:20:28 volumio volumio[867]: info: CoreCommandRouter::volumioPushState
Mar 08 15:20:28 volumio volumio[867]: info: CoreCommandRouter::executeOnPlugin: volumiodiscovery , saveDeviceInfo
Mar 08 15:20:28 volumio volumio[867]: info: CoreStateMachine::setRandom null
Mar 08 15:20:28 volumio volumio[867]: info: CoreStateMachine::pushState
Mar 08 15:20:28 volumio volumio[867]: info: CoreStateMachine::getState
Mar 08 15:20:28 volumio volumio[867]: info: CorePlayQueue::getTrack 0
Mar 08 15:20:28 volumio volumio[867]: info: CoreCommandRouter::volumioPushState
Mar 08 15:20:28 volumio volumio[867]: info: CoreCommandRouter::executeOnPlugin: volumiodiscovery , saveDeviceInfo
Mar 08 15:20:29 volumio volumio[867]: info: Starting Shairport Sync
Mar 08 15:20:29 volumio volumio[867]: info: Starting Shairport Sync
Mar 08 15:20:29 volumio volumio[867]: Discovery: adding dec61284-90f4-4246-9f82-858f646416ce
Mar 08 15:20:29 volumio sudo[1010]: volumio : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/systemctl restart shairport-sync
Mar 08 15:20:29 volumio volumio[867]: info: mDNS: Found device Volumio
Mar 08 15:20:29 volumio sudo[1010]: pam_unix(sudo:session): session opened for user root by (uid=0)
Mar 08 15:20:29 volumio sudo[1012]: volumio : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/systemctl restart shairport-sync
Mar 08 15:20:29 volumio sudo[1012]: pam_unix(sudo:session): session opened for user root by (uid=0)
Mar 08 15:20:29 volumio systemd[1]: Starting Shairport Sync - AirPlay Audio Receiver...
Mar 08 15:20:29 volumio systemd[1]: Started Shairport Sync - AirPlay Audio Receiver.
Mar 08 15:20:29 volumio sudo[1010]: pam_unix(sudo:session): session closed for user root
Mar 08 15:20:29 volumio sudo[1014]: volumio : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/systemctl start upmpdcli.service
Mar 08 15:20:29 volumio systemd[1]: Stopping Shairport Sync - AirPlay Audio Receiver...
Mar 08 15:20:29 volumio systemd[1]: Starting Shairport Sync - AirPlay Audio Receiver...
Mar 08 15:20:29 volumio sudo[1014]: pam_unix(sudo:session): session opened for user root by (uid=0)
Mar 08 15:20:29 volumio systemd[1]: Started Shairport Sync - AirPlay Audio Receiver.
Mar 08 15:20:29 volumio sudo[1012]: pam_unix(sudo:session): session closed for user root
Mar 08 15:20:29 volumio sudo[1024]: volumio : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/sbin/ifconfig wlan0
Mar 08 15:20:29 volumio systemd[1]: Starting UPnP Renderer front-end to MPD...
Mar 08 15:20:30 volumio systemd[1]: Started UPnP Renderer front-end to MPD.
Mar 08 15:20:30 volumio sudo[1014]: pam_unix(sudo:session): session closed for user root
Mar 08 15:20:30 volumio sudo[1024]: pam_unix(sudo:session): session opened for user root by (uid=0)
Mar 08 15:20:30 volumio sudo[1024]: pam_unix(sudo:session): session closed for user root
Mar 08 15:20:31 volumio volumio[867]: info: Upmpdcli Daemon Started
Mar 08 15:20:31 volumio volumio[867]: info: Shairport-Sync Started
Mar 08 15:20:31 volumio volumio[867]: Error adding Membership: Error: addMembership EINVAL
Mar 08 15:20:31 volumio volumio[867]: info: Shairport-Sync Started
Mar 08 15:20:31 volumio volumio[867]: info: Connecting to daemon
Mar 08 15:20:31 volumio volumio[867]: info: [MyVolumio PluginManager] Adding plugin bluetooth to plan superstar
Mar 08 15:20:31 volumio volumio[867]: info: [MyVolumio PluginManager] Adding plugin cd_controller to plan superstar
Mar 08 15:20:31 volumio volumio[867]: info: [MyVolumio PluginManager] Adding plugin smart_inputs to plan superstar
Mar 08 15:20:31 volumio volumio[867]: info: [MyVolumio PluginManager] Adding plugin hi_res_audio to plan superstar
Mar 08 15:20:31 volumio volumio[867]: info: [MyVolumio PluginManager] Adding plugin bluetooth to plan virtuoso
Mar 08 15:20:31 volumio volumio[867]: info: [MyVolumio PluginManager] Adding plugin cd_controller to plan virtuoso
Mar 08 15:20:31 volumio volumio[867]: info: Adding plugin bluetooth to MyMusic Plugins
Mar 08 15:20:31 volumio volumio[867]: info: Adding plugin cd_controller to MyMusic Plugins
Mar 08 15:20:31 volumio volumio[867]: info: Adding plugin smart_inputs to MyMusic Plugins
Mar 08 15:20:31 volumio volumio[867]: info: [MyVolumio PluginManager] Loading plugin "my_volumio"...
Mar 08 15:20:39 volumio volumio[867]: info: [MyVolumio PluginManager] Loading plugin "streaming_services"...
Mar 08 15:20:45 volumio volumio[867]: info: [MyVolumio PluginManager] MyVolumio plugin successfully loaded
Mar 08 15:20:45 volumio volumio[867]: info: [MyVolumio PluginManager] Starting plugin system_controller.my_volumio
Mar 08 15:20:45 volumio volumio[867]: info: CoreCommandRouter::executeOnPlugin: system , getConfigParam
Mar 08 15:20:45 volumio volumio[867]: info: CoreCommandRouter::executeOnPlugin: system , getConfigParam
Mar 08 15:20:45 volumio volumio[867]: info: CoreCommandRouter::executeOnPlugin: system , getConfigParam
Mar 08 15:20:45 volumio volumio[867]: info: Starting MyVolumio Remote Streaming Endpoints
Mar 08 15:20:45 volumio volumio[867]: info: [MyVolumio PluginManager] Streaming Services plugin successfully loaded
Mar 08 15:20:45 volumio volumio[867]: info: [MyVolumio PluginManager] Starting plugin music_service.streaming_services
Mar 08 15:20:45 volumio volumio[867]: info: Streaming services startup
Mar 08 15:20:45 volumio volumio[867]: info: Starting Streaming Daemon
Mar 08 15:20:45 volumio volumio[867]: info: MyVolumio not started
Mar 08 15:20:45 volumio volumio[867]: info: Initializing device activation check
Mar 08 15:20:45 volumio volumio[867]: info: CoreCommandRouter::executeOnPlugin: system , getConfigParam
Mar 08 15:20:45 volumio sudo[1060]: volumio : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/systemctl restart volumio-streaming-daemon.service
Mar 08 15:20:45 volumio sudo[1060]: pam_unix(sudo:session): session opened for user root by (uid=0)
Mar 08 15:20:45 volumio systemd[1]: Stopping Volumio Streaming Daemon...
Mar 08 15:20:45 volumio volumio[867]: info: [MyVolumio PluginManager] MyVolumio plugin successfully started
Mar 08 15:20:45 volumio systemd[1]: Starting Volumio Streaming Daemon...
Mar 08 15:20:45 volumio systemd[1]: Started Volumio Streaming Daemon.
Mar 08 15:20:45 volumio sudo[1060]: pam_unix(sudo:session): session closed for user root
Mar 08 15:20:45 volumio volumio-streaming-daemon[1066]: ############################
Mar 08 15:20:45 volumio volumio-streaming-daemon[1066]: # Volumio Streaming Daemon #
Mar 08 15:20:45 volumio volumio-streaming-daemon[1066]: # Running on port 7777     #
Mar 08 15:20:45 volumio volumio-streaming-daemon[1066]: ############################
Mar 08 15:20:47 volumio volumio[867]: info: CoreCommandRouter::volumioAddToBrowseSources[object Object]
Mar 08 15:20:47 volumio volumio[867]: info: [1583680847525] CoreMusicLibrary::Adding element Spotify
Mar 08 15:20:47 volumio volumio[867]: info: CoreCommandRouter::executeOnPlugin: my_music , getDisabledSources
Mar 08 15:20:47 volumio volumio[867]: /usr/bin/md5sum: /sys/class/net/eth0/address: No such file or directory
Mar 08 15:20:47 volumio volumio[867]: info: CoreCommandRouter::executeOnPlugin: system , getConfigParam
Mar 08 15:20:47 volumio volumio[867]: info: CoreCommandRouter::executeOnPlugin: system , getSystemVersion
Mar 08 15:20:47 volumio volumio[867]: info: CoreCommandRouter::executeOnPlugin: system , getConfigParam
Mar 08 15:20:48 volumio volumio[867]: info: FIRST BRANCH
Mar 08 15:20:48 volumio volumio[867]: info: CoreCommandRouter::volumioGetState
Mar 08 15:20:48 volumio volumio[867]: info: CoreStateMachine::getState
Mar 08 15:20:48 volumio volumio[867]: info: CorePlayQueue::getTrack 0
Mar 08 15:20:48 volumio sudo[1076]: volumio : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/sbin/ifconfig wlan0
Mar 08 15:20:48 volumio sudo[1076]: pam_unix(sudo:session): session opened for user root by (uid=0)
Mar 08 15:20:48 volumio sudo[1076]: pam_unix(sudo:session): session closed for user root
Mar 08 15:20:49 volumio volumio[867]: info: New Spotify access token = BQDuav33OA8Sgt6ZlrU4n4Wa0urFmG04ApBTnHJesdepQdHqixEsJCGFIXe3iv-9JPSNM1_BUWU0iGkTZofOeeW_YzQBRX6ZKIu7knvvu-7CsKE4XiQmsr9egQ0y7Zks3vqmvTUag-EO_hYUP8funiM_u-crX8mmwdgrho2dZnBI7CnR4tds3UYZ3F7K1A
Mar 08 15:20:49 volumio volumio[867]: info: Spotify credentials grant success - running version from March 24, 2019
Mar 08 15:20:49 volumio volumio[867]: info: An error occurred while listing Spotify featured playlists WebapiError: Unauthorized
Mar 08 15:20:49 volumio volumio[867]: info: An error occurred while listing Spotify categories WebapiError: Unauthorized
Mar 08 15:20:50 volumio volumio[867]: info: Fetching Streaming Services browse cache
Mar 08 15:20:51 volumio volumio[867]: info: CoreCommandRouter::volumioRemoveToBrowseSourcesQOBUZ
Mar 08 15:20:51 volumio volumio[867]: info: CoreCommandRouter::executeOnPlugin: my_music , getDisabledSources
Mar 08 15:20:51 volumio volumio[867]: info: CoreCommandRouter::volumioRemoveToBrowseSourcesTIDAL
Mar 08 15:20:51 volumio volumio[867]: info: CoreCommandRouter::executeOnPlugin: my_music , getDisabledSources
Mar 08 15:20:53 volumio volumio[867]: info: CoreCommandRouter::volumioGetVisibleSources
Mar 08 15:20:53 volumio volumio[867]: info: CoreCommandRouter::executeOnPlugin: my_music , getDisabledSources
Mar 08 15:20:53 volumio volumio[867]: info: CoreCommandRouter::volumioGetState
Mar 08 15:20:53 volumio volumio[867]: info: CoreStateMachine::getState
Mar 08 15:20:53 volumio volumio[867]: info: CorePlayQueue::getTrack 0
Mar 08 15:20:53 volumio volumio[867]: info: CoreCommandRouter::volumioGetQueue
Mar 08 15:20:53 volumio volumio[867]: info: CoreStateMachine::getQueue
Mar 08 15:20:53 volumio volumio[867]: info: CorePlayQueue::getQueue
Mar 08 15:20:53 volumio volumio[867]: info: Listing playlists
Mar 08 15:20:53 volumio sudo[1104]: volumio : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/sbin/ifconfig wlan0
Mar 08 15:20:53 volumio volumio[867]: info: CoreCommandRouter::executeOnPlugin: multiroom , getMultiroom
Mar 08 15:20:53 volumio sudo[1104]: pam_unix(sudo:session): session opened for user root by (uid=0)
Mar 08 15:20:53 volumio sudo[1104]: pam_unix(sudo:session): session closed for user root
Mar 08 15:20:53 volumio sudo[1107]: volumio : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/sbin/ifconfig wlan0
Mar 08 15:20:53 volumio sudo[1107]: pam_unix(sudo:session): session opened for user root by (uid=0)
Mar 08 15:20:53 volumio sudo[1107]: pam_unix(sudo:session): session closed for user root
`

**Comment by dubaleeiro** [comment]
I have just tried again with a different SD-Card and fresh Volumio install: same issue :)
